### ISSUE TITLE
Coverage reports fail on Travis

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#4918]
## Expected behavior
The coverage script should run after tests complete, and post a coverage report to coveralls.io.
## Current behavior
_Please include any error messages from the browser console and/or screenshots_
coverage fails with an error because `.nyc_output` is missing.
```
> nyc report --reporter=text-lcov | coveralls
/home/travis/build/zooniverse/Panoptes-Front-End/node_modules/nyc/node_modules/yargs/yargs.js:1133
      else throw err
           ^
Error: ENOENT: no such file or directory, scandir '/home/travis/build/zooniverse/Panoptes-Front-End/.nyc_output'
    at Object.fs.readdirSync (fs.js:904:18)
    at NYC.eachReport (/home/travis/build/zooniverse/Panoptes-Front-End/node_modules/nyc/index.js:525:31)
    at NYC.getCoverageMapFromAllCoverageFiles (/home/travis/build/zooniverse/Panoptes-Front-End/node_modules/nyc/index.js:424:8)
```
## Steps to replicate
Commit to master and check the end of the Travis CI log.

**Comment by eatyourgreens** [comment]
`test-travis` isn't actually running `nyc`. My bad.
